### PR TITLE
Try removing OSAT Remote

### PR DESCRIPTION
**Pull request by banfai**
Link #11

### CODE REVIEW

**Comment by idavydov** [comment]
Did I get it correctly?

This removes Remotes path of the OSAT package, meaning that it will be not installed in CI. And this will lead to an empty vignette.

Is that right, @banfai?

**Comment by banfai** [comment]
> Did I get it correctly?
> 
> This removes Remotes path of the OSAT package, meaning that it will be not installed in CI. And this will lead to an empty vignette.
> 
> Is that right, @banfai?

No, this way it is installed. Apparently for `bioc` packages the `Remotes` section is not needed? I've found contradiction information about this... We've also had some conversation about this with @klmr, concluding that `remotes`, `pak`, `pkgdepends`, `gitcreds`, etc are a mess at the moment.
I still need to check if GRAN works like this.
In the CI artifact https://github.com/bedapub/designit/suites/9820420276/artifacts/472816872
the vignette is rendered:  dev/articles/osat.html

**Comment by klmr** [comment]
All that is required for Bioconductor dependencies is an (empty) [`biocViews` section](https://bioinformatics.stackexchange.com/a/3375/29) in `DESCRIPTION`.

**Comment by idavydov** [comment]
fixed in the main branch

**Pull request closed without merging**
